name: motion_solo_project
dependencies:
  - python=3.10.4
  - pip=22.2.2
  - psycopg2
  - pip:
      - django==4.1.1
      - djangorestframework==3.14.0
      - pillow==9.2.0
      - djangorestframework-simplejwt==5.2.1
      - drf-yasg==1.21.4
      - pillow==9.2.0
      - flake8==5.0.4
      - gunicorn
