# Generated by Django 4.1.1 on 2022-10-07 10:06

from django.db import migrations, models
import post.models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_rename_title_post_title_post_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, upload_to=post.models.post_directory_path),
        ),
    ]
