# Generated by Django 4.1.1 on 2022-10-07 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='owner',
        ),
    ]
