# Generated by Django 4.1.1 on 2022-10-09 11:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0008_post_is_liked_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='is_liked_by',
            field=models.ManyToManyField(blank=True, default=None, related_name='liked_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
